name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Aller dans le dossier app
        run: cd app
      - name: Installer les dépendances
        run: npm install
        working-directory: ./app
      - name: Lancer les tests
        run: npm test
        working-directory: ./app